config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :songs, only: [:new, :create, :index] do
    post :veto

    resources :votes, only: [:create]
  end

  # post '/songs/:id/veto' => 'songs#veto'

  root 'songs#index'
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user

  has_many :votes

  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs

  validates_presence_of :title, :artist

  def self.unvetoed
    where vetoed: false
  end

  def sort_letter
    letter = if artist.downcase.start_with? "a "
      artist[2]
    elsif artist.downcase.start_with? "an "
      artist[3]
    elsif artist.downcase.start_with? "the "
      artist[4]
    else
      artist[0]
    end
    letter.upcase
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  class NotAuthorizedError < StandardError; end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes
  has_many :songs
  
  def veto! song
    # song.update vetoed: true
    song.vetoed = true
    song.save!
  end

  def add_song spotify_id
    # should fetch from spotify
    songs.new spotify_id: spotify_id, artist: SecureRandom.hex(12), title: SecureRandom.hex(12)
  end

  def vote_for song
    if votes_left > 0
      votes.create! song: song
      update votes_left: votes_left - 1
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  rescue_from User::NotAuthorizedError do |e|
    sign_out current_user
    flash[:error] = "You are not authorized to view this page"
    redirect_to new_user_session_path
  end

  def require_admin!
    raise User::NotAuthorizedError unless current_user.admin?
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index]

  def index
    # FIXME: add sorting options
    @songs = Song.all
  end

  def new
    @song = Song.new
  end

  def create
    #create_params = params.require(:song).permit(:spotify_id)
    @song = current_user.add_song params[:song][:spotify_id]
    if @song.save
      redirect_to songs_path, notice: "Song created!"
    else
      render :new
    end
  end

  def veto
    song = Song.find params[:song_id]
    current_user.veto! song
    redirect_to :back, notice: "You vetoed #{song.title}"
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    song = Song.find params[:song_id]
    if current_user.vote_for song
      flash[:notice] = "Your vote has been recorded"
    else
      flash[:error] = "You are out of votes. Please wait 'til next week."
    end
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def translate_to_bootstrap flash_class
    # Translate rails conventions to bootstrap conventions
    case flash_class.to_sym
    when :notice
      :success
    when :alert
      :danger
    else
      flash_class
    end
  end

  def icon name
    "<i class='glyphicon glyphicon-#{name}'></i>".html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spotibetical</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <span>Logged in as <%= current_user.email %></span>
  <%= link_to "Log out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Log in", new_user_session_path %>
<% end %>

<div class="container">
  <% flash.each do |flash_type, message| %>
    <div class="alert alert-<%= translate_to_bootstrap flash_type %>">
      <%= message %>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/songs/index.html.erb
<%= link_to "Add Song", new_song_path, class: "btn btn-success" %>

<h1>Suggested Songs</h1>

<form style='float: left; padding: 5px;' action="/display" method="GET">
  <input name="sort" value="alpha" type="hidden">
  <button class="btn btn-sm btn-primary">Sort by artist name</button>
</form>
<form style='float: left; padding: 5px;' action="/display" method="GET">
  <input type="hidden">
  <button class="btn btn-sm btn-success">Sort by date suggested</button>
</form>

  <% if current_user %>
    <div align="right">
      <button form='voting' class="btn btn-danger">Submit Vote</button>
    </div>
  <% end %>
  <input type="hidden" name ='_method' value='PATCH'>

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Artist</th>
        <th>Title</th>
        <th>Preview</th>
        <th>Current Votes</th>
        <% if current_user %>
          <th>Vote</th>
          <th>Veto</th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @songs.each do |song| %>
        <tr>
          <td><%= song["artist"]%></td>
          <td><%= song["title"]%></td>
          <td>
            <button><a href=<%= song["preview_link"]%>>♬</a></button>
          </td>
          <td><%= song.votes.count %></td>
          <% if current_user %>
            <td>
              <%= button_to "Vote", song_votes_path(song), class: "btn btn-default" %>
              <!--<div class='checkbox'>
                <label>
                  <% song_id=song["id"]%>
                  <input name="songs[]" type='checkbox' value=<%=song_id%>>VOTE
                </label>
              </div>-->
            </td>
            <td>
              <% if song.vetoed? %>
                <button class="btn btn-danger">VETOED</button>
              <% else %>
                <%= form_tag song_veto_path(song), method: :post do %>
                  <button class="btn btn-success">VETO</button>  
                <% end %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>

  </tbody>
</table>

app/views/songs/new.html.erb
<% if @song.errors.any? %>
  <ul>
    <% @song.errors.full_messages.each do |err| %>
      <li><%= err %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @song do |f| %>
  <%= f.label :spotify_id %>
  <%= f.text_field :spotify_id, class: 'form-control' %>
  <button class="btn btn-default">Save</button>
<% end %>